### ISSUE TITLE
Upgrade to support AFNetworking 3.0?

### ISSUE THREAD

**Issue by andrewhavens** [rubymotion-community/afmotion#108]
According to issue #99, there used to be an issue in RubyMotion preventing AFMotion from using AFNetworking > 2.5.x. At minimum, I think we should remove the lock on the 2.5 series. At best, I'd like to see us upgrade to support 3.0.

The latest version of AFNetworking (3.0.4) includes a number of bug fixes and adds support for watchOS and tvOS. However, there may be a number of architectural upgrades required to support 3.0: [AFNetworking 3.0 Migration Guide](https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide)

Just reporting this to bring it to the attention of the RubyMotion community.

**Comment by holgersindbaek** [comment]
+1

**Comment by TheKidCoder** [comment]
Has anyone made any headway here? Haven't been able to submit a tiny update to my RM app because it's being rejected for lack of IPv6 support. Willing to take a crack at it, just don't want to duplicate anyone else's effort.

**Comment by andrewhavens** [comment]
AFMotion has been updated to use AFNetworking v4 in #116

**Comment by andrewhavens** [comment]
Version 3.0 has just been released which upgrades AFNetworking to 4.0.
