### ISSUE TITLE
Would really like to see update to AFNetworking 4.0?

### ISSUE THREAD

**Issue by clintpeterson** [rubymotion-community/afmotion#115]
Apple is now rejecting new apps using UIWebview, which AFNetworking removed in 4.0.0.

ITMS-90809: Deprecated API Usage

Many Thanks!

**Comment by andrewhavens** [comment]
This has been fixed in #116

**Comment by andrewhavens** [comment]
Version 3.0 has just been released which upgrades AFNetworking to 4.0.
