### ISSUE TITLE
Extensions won't compile 

### ISSUE THREAD

**Issue by rromanchuk** [rubymotion-community/afmotion#71]
rake aborted!
Pod::Podfile::StandardError: Unsupported platform `ios-extension`. Platform must be `:ios` or `:osx`.
/Users/ryan/.rvm/gems/ruby-2.1.0/gems/cocoapods-core-0.33.1/lib/cocoapods-core/podfile/target_definition.rb:354:in `set_platform'
/Users/ryan/.rvm/gems/ruby-2.1.0/gems/cocoapods-core-0.33.1/lib/cocoapods-core/podfile/dsl.rb:291:in`platform'
/Users/ryan/.rvm/gems/ruby-2.1.0/gems/motion-cocoapods-1.5.0/lib/motion/project/cocoapods.rb:72:in `initialize'
/Users/ryan/.rvm/gems/ruby-2.1.0/gems/motion-cocoapods-1.5.0/lib/motion/project/cocoapods.rb:38:in`new'
/Users/ryan/.rvm/gems/ruby-2.1.0/gems/motion-cocoapods-1.5.0/lib/motion/project/cocoapods.rb:38:in `pods'
/Users/ryan/.rvm/gems/ruby-2.1.0/gems/afmotion-2.4.1/lib/afmotion.rb:18:in`block in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:110:in `call'
/Library/RubyMotion/lib/motion/project/config.rb:110:in`block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:110:in `each'
/Library/RubyMotion/lib/motion/project/config.rb:110:in`setup'
/Library/RubyMotion/lib/motion/project/app.rb:66:in `config'

**Comment by andrewhavens** [comment]
Closing this issue since it is super old. Upgrade to v3.0 and let us know if you're still having problems.
