### ISSUE TITLE
Multipart Post timeout issues in iOS8

### ISSUE THREAD

**Issue by pollingj** [rubymotion-community/afmotion#77]
Hi, 

I appear to be having issues with the Multipart Post in iOS8.  It works fine in iOS7, but not iOS8.  The error I'm getting back from the result object contains the below

```
description="The request timed out.", code=-1001
```

I'm guessing this may well be more of an AFNetworking issue, but I was just wondering if this was a known problem?

The request isn't even hitting the server in iOS8, which is really odd.

**Comment by jasdeepsingh** [comment]
Using `afmotion 2.5` and this still seems to be an issue for me.

**Comment by andrewhavens** [comment]
Closing this issue since it is super old. Upgrade to v3.0 and let us know if you're still having problems.
