### ISSUE TITLE
deprecate token authentication

### ISSUE THREAD

**Issue by robj** [rubymotion-community/afmotion#81]
This has been deprecated in AFNetworking as per

https://github.com/AFNetworking/AFNetworking/commit/cd9a80f

Currently authorization(token: ____) enforces a particular format (eg. quoting) that may be different to the server implementation.

For flexibility in token string format, best way to achieve this is use the following method:

AFMotion::Client.shared.requestSerializer.setValue(token_string, forHTTPHeaderField: "Authorization")

**Comment by andrewhavens** [comment]
Closing this issue since it is super old. Upgrade to v3.0 and let us know if you're still having problems.
