### ISSUE TITLE
statusCode calling on nil. 

### ISSUE THREAD

**Issue by TigerWolf** [rubymotion-community/afmotion#83]
If a `AFMotion::SessionClient` fails, calling `status_code` will fail. 

```
http_result.rb:29:in `status_code': undefined method `statusCode' for nil:NilClass (NoMethodError)
    from timetable_screen.rb:102:in `block in get_data'
    from operation.rb:28:in `block in failure_block:'
```

https://github.com/clayallsopp/afmotion/blob/master/lib/afmotion/http_result.rb#L29
https://github.com/clayallsopp/afmotion/blob/master/lib/afmotion/operation.rb#L28

From doing a quick search, it may be related to https://github.com/clayallsopp/afmotion/issues/33

Currently using version 2.5

My current work around is to check if result.task.response is nil
`unless result.task.response == nil`

**Comment by katsuyoshi** [comment]
I've got a same issue If a server is not launched.

**Comment by andrewhavens** [comment]
Closing this issue since it is super old. Upgrade to v3.0 and let us know if you're still having problems.
